version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_BASE_URL: https://neureal.site/api
      PUBLIC_SITE_URL: https://neureal.site

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      SITE_URL: https://neureal.site
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SECRET: ${SUPABASE_SECRET}
      # ... otras variables

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend