version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - PUBLIC_API_BASE_URL=https://neureal.site/api
      - PUBLIC_SITE_URL=https://neureal.site
    networks:
      neureal-net:
        aliases:
          - frontend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file: 
      - apps/backend/.env
    networks:
      neureal-net:
        aliases:
          - backend
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      neureal-net:
        aliases:
          - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/ssl-overrides.conf:/etc/nginx/ssl-overrides.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      neureal-net:
        aliases:
          - nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      neureal-net:
        aliases:
          - certbot
    restart: unless-stopped

networks:
  neureal-net:
    driver: bridge
    attachable: true

volumes:
  redis-data: