version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - PUBLIC_API_BASE_URL=https://neureal.site/api
      - PUBLIC_SITE_URL=https://neureal.site
    restart: unless-stopped
    networks:
      - neureal-net

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      - SITE_URL=https://neureal.site
      - PORT=8000
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - neureal-net

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - neureal-net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - neureal-net

networks:
  neureal-net:
    driver: bridge