version: "3.8"

services:
  backend:
    image: ghcr.io/yourusername/neureal-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: unless-stopped

  frontend:
    image: ghcr.io/yourusername/neureal-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
