version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - PUBLIC_API_BASE_URL=https://neureal.site/api
      - PUBLIC_SITE_URL=https://neureal.site
    networks:
      - neureal-net
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file: 
      - apps/backend/.env
    networks:
      - neureal-net
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - neureal-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - neureal-net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: sh -c "while true; do sleep 12h; certbot renew; done;"
    networks:
      - neureal-net
    # SE ELIMINÓ LA LÍNEA DUPLICADA restart: unless-stopped

networks:
  neureal-net:
    driver: bridge

volumes:
  redis-data: